# Generated by Django 5.2.12 on 2026-03-19 20:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_name', models.CharField(max_length=50)),
                ('score', models.PositiveIntegerField()),
                ('wave_reached', models.PositiveIntegerField()),
                ('enemies_killed', models.PositiveIntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'leaderboard entries',
                'ordering': ['-score'],
            },
        ),
    ]
