# Generated by Django 5.2.12 on 2026-04-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_highscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='score',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
