# Generated by Django 5.2.12 on 2026-04-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_seed_sample_high_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='highscore',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=6),
        ),
    ]
